name: Deploy Static Site to GitHub Pages

on:
  push:
    branches: [ main ]

concurrency:
  group: "pages-${{ github.ref }}"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/configure-pages@v3
    - uses: actions/upload-pages-artifact@v2
      with:
        path: .  # Deploys everything in root
    - name: Deploy
      uses: actions/deploy-pages@v2
